[package]
name = "asymcrypt-lab3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
malachite = "0.4.4"
rayon = "1.8.0"
rand = "0.8.5"
num-bigint = "0.4.4"
num-traits = "0.2.17"
num-integer = "0.1.45"